export const INITIALIZE = 'INITIALIZE';
export const PAGE_ERROR = 'PAGE_ERROR';

export const CHANGE_VALUE = 'CHANGE_VALUE';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const LOGIN_FORM_CHANGE_VALUE = 'LOGIN_FORM_CHANGE_VALUE';
export const LOGIN_FORM_LOGIN_STARTED = 'LOGIN_FORM_LOGIN_STARTED';
export const LOGIN_FORM_LOGIN_SUCCESS = 'LOGIN_FORM_LOGIN_SUCCESS';
export const LOGIN_FORM_LOGIN_FALIURE = 'LOGIN_FORM_LOGIN_FAILURE';
export const LOGIN_FORM_LOGOUT_SUCCESS = 'LOGIN_FORM_LOGOUT_SUCCESS';
