/* eslint no-console:0, max-len:0 */

export const INITIALIZE = 'INITIALIZE';
export const PAGE_ERROR = 'PAGE_ERROR';

export const SHARED_CHANGE_TAB = 'SHARED_CHANGE_TAB';

export const USER_CHANGE_VALUE = 'USER_CHANGE_VALUE';

export const LOGIN_FORM_CHANGE_VALUE = 'LOGIN_FORM_CHANGE_VALUE';
export const LOGIN_FORM_LOGIN_STARTED = 'LOGIN_FORM_LOGIN_STARTED';
export const LOGIN_FORM_LOGIN_SUCCESS = 'LOGIN_FORM_LOGIN_SUCCESS';
export const LOGIN_FORM_LOGIN_FALIURE = 'LOGIN_FORM_LOGIN_FAILURE';
export const LOGIN_FORM_LOGOUT_SUCCESS = 'LOGIN_FORM_LOGOUT_SUCCESS';

export const REPOS_SEARCH_FINISHED = 'REPOS_SEARCH_FINISHED';
export const REPOS_SEARCH_FETCHING = 'REPOS_SEARCH_FETCHING';

export const USERS_SEARCH_FINISHED = 'USERS_SEARCH_FINISHED';
export const USERS_SEARCH_FETCHING = 'USERS_SEARCH_FETCHING';

export const USER_SEARCH_FINISHED = 'USER_SEARCH_FINISHED';
export const USER_SEARCH_FETCHING = 'USER_SEARCH_FETCHING';

export const FOLLOWERS_SEARCH_FINISHED = 'FOLLOWERS_SEARCH_FINISHED';
export const FOLLOWERS_SEARCH_FETCHING = 'FOLLOWERS_SEARCH_FETCHING';
